os:
- linux
language: ruby
rvm:
- 2.2.0
- 2.0.0
before_install:
- sudo apt-get update
- gem update --system
- gem --version
before_script:
- bundle exec rake db:create db:migrate db:schema:load
notifications:
  email:
    recipients:
    - tom.jcox@icloud.com
    on_success: change
    on_failure: change
