os:
  - linux
  # - osx

# matrix:
  # allow_failures:
    # - os: osx


language: ruby

rvm:
  - 2.2.0
  - 2.0.0

before_install:
  - sudo apt-get update
  # - brew update
  - gem update --system
  - gem --version

notifications:
  email:
    recipients:
      - tom.jcox@icloud.com
    on_success: change # default: change
    on_failure: change # default: always
