os:
- linux
language: ruby
rvm:
- 2.2.0
- 2.0.0
before_install:
- sudo apt-get update
- gem update --system
- gem --version
before_script:
- bundle exec rake db:create db:migrate db:schema:load
addons:
  code_climate:
    repo_token: 812d48041b7faafd2a04d75ecc3d59ab6e9c9586c628c9272e80cf51f56a9c62
notifications:
  on_success: change
  on_failure: change
  email:
    recipients:
    - tom.jcox@icloud.com
deploy:
  provider: heroku
  api_key:
    secure: vQi59892dFjqpdhKrPwB6dBtCC7xtPUG5uxF842jBLH1KeZrRq2eMh/oOuQdou+kfUSj/JmhjKR5DFVAi/w+ib+VM3mQmz+bjJjQAZNexA6xglXdWBMg47QjN+sHu+baw7JY50PbD3XPuGuz0gVizNY9FHtSD6Efk1giu3gZMJQ=
  app: mvweddings
  on:
    repo: crmis/weddings
