os:
- linux
language: ruby
rvm:
- 2.2.0
- 2.0.0
before_install:
- sudo apt-get update
- gem update --system
- gem --version
before_script:
- bundle exec rake db:create db:migrate db:schema:load
addons:
  code_climate:
    repo_token:
    - 812d48041b7faafd2a04d75ecc3d59ab6e9c9586c628c9272e80cf51f56a9c62
notifications:
  on_success: change
  on_failure: change
  email:
    recipients:
    - tom.jcox@icloud.com
deploy:
  api_key:
    secure: QtSt0Dm3spUovzGaNYyReL2iPsd7Aii0PIH7EAYsJ2takkoXqqO7g0CMUMuvcJHbwOxYxEJ+O7z4v3KO21ys+VX9TekGRpOVcxA3dHCxHkEQCIgpSLxAHXAWbHEraLeyd9ge7B17IlYHCxGY+y4YUEWLPBveReJmn+VH6Xrw7jQ=
