os:
  - linux
  # - osx

# matrix:
  # allow_failures:
    # - os: osx


language: ruby

rvm:
  - 2.2.0
  - 2.0.0

before_install:
  - sudo apt-get update
  # - brew update
  - gem update --system
  - gem --version

before_script:
  - bundle exec rake db:create db:migrate db:schema:load

addons:
  code_climate:
      repo_token: 812d48041b7faafd2a04d75ecc3d59ab6e9c9586c628c9272e80cf51f56a9c62

notifications:
  email:
    recipients:
      - tom.jcox@icloud.com
    on_success: change # default: change
    on_failure: change # default: always
